integrations:
  - name: nri-mysql
    interval: 15s
    timeout: 30s
    inventory_source: config/mysql
    env:
      HOSTNAME: ${MYSQL_HOST}
      PORT: ${MYSQL_PORT}
      USERNAME: ${MYSQL_USER}
      PASSWORD: ${MYSQL_PASSWORD}
      DATABASE: ${MYSQL_DATABASE}
      COLLECT_ALL_DATABASES: "true"
      
      # Enable query performance monitoring
      ENABLE_QUERY_MONITORING: "true"
      ENABLE_SLOW_QUERIES: "true"
      ENABLE_EXTENDED_METRICS: "true"
      ENABLE_INNODB_METRICS: "true"
      ENABLE_INNODB_METRICS_AS_SAMPLES: "true"
      ENABLE_GLOBAL_STATUS_METRICS: "true"
      
      # Metrics collection categories
      ENABLE_SLAVE_METRICS: "true"
      ENABLE_PROCESSLIST_METRICS: "true"
      ENABLE_TABLE_SCHEMA_METRICS: "true"
      ENABLE_TABLESPACE_METRICS: "true"
      
      # Additional settings for query monitoring
      TIMEOUT: "30"
      STATUS_METRICS_QUERY_RETRY_COUNT: "3"
      ENABLE_EXTENDED_SLOW_QUERIES: "true"
      ENABLE_EXPLAIN_SLOW_QUERIES: "true"
      
      # Custom queries can be added here
      CUSTOM_METRICS_QUERY: |
        SELECT COUNT(*) as 'performance_test.count',
        AVG(integer_value) as 'performance_test.avg_integer',
        MAX(integer_value) as 'performance_test.max_integer',
        MIN(integer_value) as 'performance_test.min_integer'
        FROM performance_test
