integrations:
  - name: nri-mysql
    interval: 15s
    timeout: 30s
    inventory_source: config/mysql
    config:
      hostname: ${MYSQL_HOST}
      port: ${MYSQL_PORT}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      database: ${MYSQL_DATABASE}
      collect_all_databases: true
      
      # Enable query performance monitoring
      metrics: true
      slow_queries: true
      extended_metrics: true
      extended_innodb_metrics: true
      extended_innodb_metrics_as_samples: true
      global_stats: true
      
      # Metrics collection categories
      collect_slave_metrics: true
      collect_processlist_metrics: true
      collect_table_schema_metrics: true
      collect_tablespace_metrics: true
      
      # Additional settings for query monitoring
      timeout: 30
      status_metrics_query_retry_count: 3
      enable_extended_slow_queries: true
      explain_slow_queries: true
      
      # Custom queries can be added here
      custom_metrics_query:
        - query: |
            SELECT COUNT(*) as 'performance_test.count',
            AVG(integer_value) as 'performance_test.avg_integer',
            MAX(integer_value) as 'performance_test.max_integer',
            MIN(integer_value) as 'performance_test.min_integer'
            FROM performance_test
          database: ${MYSQL_DATABASE}
