integrations:
  - name: nri-mysql
    interval: 15s
    timeout: 30s
    inventory_source: config/mysql
    env:
      HOSTNAME: ${MYSQL_HOST}
      PORT: ${MYSQL_PORT}
      USERNAME: ${MYSQL_USER}
      PASSWORD: ${MYSQL_PASSWORD}
      DATABASE: ${MYSQL_DATABASE}
      COLLECT_ALL_DATABASES: "1"
      
      # Enable query performance monitoring
      METRICS: "1"
      SLOW_QUERIES: "1"
      EXTENDED_METRICS: "1"
      EXTENDED_INNODB_METRICS: "1"
      EXTENDED_INNODB_METRICS_AS_SAMPLES: "1"
      GLOBAL_STATS: "1"
      
      # Metrics collection categories
      COLLECT_SLAVE_METRICS: "1"
      COLLECT_PROCESSLIST_METRICS: "1"
      COLLECT_TABLE_SCHEMA_METRICS: "1"
      COLLECT_TABLESPACE_METRICS: "1"
      
      # Additional settings for query monitoring
      TIMEOUT: "30"
      STATUS_METRICS_QUERY_RETRY_COUNT: "3"
      EXTENDED_SLOW_QUERIES: "1"
      EXPLAIN_SLOW_QUERIES: "1"
      
      # Custom queries can be added here
      CUSTOM_METRICS_QUERY: |
        SELECT COUNT(*) as 'performance_test.count',
        AVG(integer_value) as 'performance_test.avg_integer',
        MAX(integer_value) as 'performance_test.max_integer',
        MIN(integer_value) as 'performance_test.min_integer'
        FROM performance_test
