integrations:
  - name: nri-postgresql
    interval: 15s
    timeout: 30s
    inventory_source: config/postgresql
    config:
      hostname: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}
      collection_list: [ALL]
      
      # Enable query performance monitoring
      metrics: true
      collect_statements: true
      extended_metrics: true
      enable_default_metrics_highlights: true
      
      # Metrics collection categories
      collect_metrics_from_all_databases: true
      collect_db_lock_metrics: true
      collect_db_bloat_metrics: true
      collect_db_vacuum_metrics: true
      collect_pg_stat_statements: true
      collect_pg_stat_activity: true
      
      # Set pg_stat_statements and pg_stat_activity queries
      pg_stat_statements_metrics_limit: 50
      pg_stat_activity_metrics_limit: 50
      
      # Custom queries for monitoring
      custom_metrics_query:
        - query: |
            SELECT 
              COUNT(*) as test_count,
              AVG(integer_value) as avg_integer,
              MAX(integer_value) as max_integer,
              MIN(integer_value) as min_integer
            FROM test_monitoring.performance_test
          database: ${POSTGRES_DATABASE}
