integrations:
  - name: nri-postgresql
    interval: 15s
    timeout: 30s
    inventory_source: config/postgresql
    env:
      HOSTNAME: ${POSTGRES_HOST}
      PORT: ${POSTGRES_PORT}
      USERNAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE: ${POSTGRES_DATABASE}
      COLLECTION_LIST: "ALL"
      
      # Enable query performance monitoring
      EXTENDED_METRICS: "1"
      DEFAULT_METRICS_HIGHLIGHTS: "1"
      ENABLE_QUERY_MONITORING: "1"
      
      # Metrics collection categories
      METRICS_FROM_ALL_DATABASES: "1"
      DB_LOCK_METRICS: "1"
      DB_BLOAT_METRICS: "1"
      DB_VACUUM_METRICS: "1"
      PG_STAT_STATEMENTS: "1"
      PG_STAT_ACTIVITY: "1"
      
      # Set pg_stat_statements and pg_stat_activity queries
      PG_STAT_STATEMENTS_LIMIT: "50"
      PG_STAT_ACTIVITY_LIMIT: "50"
      
      # Custom queries for monitoring
      CUSTOM_METRICS_QUERY: |
        SELECT 
          COUNT(*) as test_count,
          AVG(integer_value) as avg_integer,
          MAX(integer_value) as max_integer,
          MIN(integer_value) as min_integer
        FROM test_monitoring.performance_test
