---
integrations:
  - name: nri-postgresql
    interval: 15s
    exec:
      - /var/db/newrelic-infra/newrelic-integrations/bin/nri-postgresql
    config:
      hostname: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      collection_list: "ALL"
      enable_ssl: false # Set to true for production
      enable_query_monitoring: true
      query_monitoring_response_time_threshold: 500
      query_monitoring_fetch_interval: 15
    inventory_source: config/postgres
    labels:
      env: test
      database_type: postgresql
      test_run: ${TEST_RUN_ID:-default}