name: Docker Validation Tests (Quick Smoke Test)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-validation.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-validation.yml'
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1
      
      - name: Build Docker image (Smoke Test)
        run: |
          docker build -t newrelic-infra:latest .
          docker images
      
      - name: Run basic image validation test
        run: |
          chmod +x testing/tests/image_validation/layer_test.sh
          ./testing/tests/image_validation/layer_test.sh
