name: Docker Validation Framework Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docker/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  linux-tests:
    name: Run Tests on Linux
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Verify Docker installation
        run: docker --version
        
      - name: Set up test environment
        run: |
          cd docker
          chmod +x bin/*.sh lib/*.sh tests/unit/*.sh tests/image_validation/*.sh
          
      - name: Run unit tests
        run: |
          cd docker
          docker run --rm -v ${{ github.workspace }}/docker:/app alpine:latest sh -c "cd /app && chmod +x /app/lib/*.sh /app/tests/unit/*.sh && /app/tests/unit/environment_test.sh"
        
      - name: Run image validation tests
        run: |
          cd docker
          docker run --rm -v ${{ github.workspace }}/docker:/app -v /var/run/docker.sock:/var/run/docker.sock alpine:latest sh -c "cd /app && apk add --no-cache docker-cli && chmod +x /app/lib/*.sh /app/tests/image_validation/*.sh && /app/tests/image_validation/layer_test.sh"
      
      - name: Run integration tests
        run: |
          cd docker
          docker-compose up -d
          docker-compose ps
          docker-compose run test-runner
          docker-compose down
          
  windows-tests:
    name: Run Tests on Windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Verify Docker installation
        run: docker --version
        
      - name: Set file permissions
        shell: bash
        run: |
          cd docker
          chmod +x bin/*.sh lib/*.sh tests/unit/*.sh tests/image_validation/*.sh
      
      - name: Run unit tests in Docker
        shell: bash
        run: |
          cd docker
          docker run --rm -v "$(pwd):/app" alpine:latest sh -c "cd /app && chmod +x /app/lib/*.sh /app/tests/unit/*.sh && /app/tests/unit/environment_test.sh"
    
      - name: Run image validation tests in Docker
        shell: bash
        run: |
          cd docker
          docker run --rm -v "$(pwd):/app" -v //var/run/docker.sock:/var/run/docker.sock alpine:latest sh -c "cd /app && apk add --no-cache docker-cli && chmod +x /app/lib/*.sh /app/tests/image_validation/*.sh && /app/tests/image_validation/layer_test.sh"
