name: Docker Validation Framework Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  linux-tests:
    name: Run Tests on Linux
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Set up Docker Compose
        run: |
          # Install Docker Compose if not available
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
          docker-compose --version
        
      - name: Verify Docker installation
        run: docker --version
        
      - name: Set up test environment
        run: |
          chmod +x testing/bin/*.sh testing/lib/*.sh testing/tests/unit/*.sh testing/tests/image_validation/*.sh testing/bin/unified/*.sh
          
      - name: Run unit tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/app alpine:latest sh -c "cd /app && chmod +x /app/testing/lib/*.sh /app/testing/tests/unit/*.sh && /app/testing/tests/unit/environment_test.sh"
        
      - name: Run image validation tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -v /var/run/docker.sock:/var/run/docker.sock alpine:latest sh -c "cd /app && apk add --no-cache docker-cli && chmod +x /app/testing/lib/*.sh /app/testing/tests/image_validation/*.sh && /app/testing/tests/image_validation/layer_test.sh"
      
      - name: Run integration tests
        run: |
          docker-compose up -d
          docker-compose ps
          docker-compose run test-runner
          docker-compose down
          
      - name: Run database monitoring tests
        run: |
          echo "Running database monitoring tests"
          docker-compose up -d
          sleep 30 # Allow services to initialize
          docker run --rm --network host -v ${{ github.workspace }}:/app alpine:latest sh -c "cd /app && chmod +x /app/testing/tests/db_monitoring/*.sh && /app/testing/tests/db_monitoring/db_integration_test.sh"
          docker-compose down
