name: Integration Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docker/**'
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          chmod +x testing/tests/run_all_tests.sh
          chmod +x testing/tests/config_validation/*.sh
          chmod +x testing/tests/integration/mysql/*.sh
          chmod +x testing/tests/integration/postgres/*.sh
          chmod +x testing/tests/security/*.sh
          chmod +x testing/lib/*.sh
      
      - name: Create output directory
        run: mkdir -p testing/output
      
      - name: Start the environment
        run: |
          export NEW_RELIC_LICENSE_KEY=dummy012345678901234567890123456789
          docker compose -f docker-compose.yml up -d --build
      
      - name: Wait for containers to be ready
        run: |
          echo "Waiting for containers to be healthy..."
          timeout 300 bash -c 'until docker ps | grep -q "(healthy)"; do sleep 5; done'
      
      - name: Run tests
        run: |
          docker exec test-runner sh -c "/testing/tests/run_all_tests.sh"
      
      - name: Collect logs
        if: always()
        run: |
          mkdir -p logs
          docker logs test-newrelic-infra > logs/newrelic-infra.log 2>&1 || true
          docker logs test-mysql > logs/mysql.log 2>&1 || true
          docker logs test-postgres > logs/postgres.log 2>&1 || true
          docker logs mock-newrelic > logs/mockbackend.log 2>&1 || true
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-linux
          path: docker/logs/
      
      - name: Clean up
        if: always()
        run: docker compose down -v

  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./docker
        shell: bash
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Start the environment
        run: |
          export NEW_RELIC_LICENSE_KEY=dummy012345678901234567890123456789
          docker compose -f docker-compose.yml up -d --build
      
      - name: Wait for containers to be ready
        run: |
          echo "Waiting for containers to be healthy..."
          timeout 300 bash -c 'until docker ps | grep -q "(healthy)"; do sleep 5; done'
        shell: bash
      
      - name: Run tests
        run: |
          docker exec test-runner sh -c "/testing/tests/run_all_tests.sh"
      
      - name: Collect logs
        if: always()
        run: |
          mkdir -p logs
          docker logs test-newrelic-infra > logs/newrelic-infra.log 2>&1 || true
          docker logs test-mysql > logs/mysql.log 2>&1 || true
          docker logs test-postgres > logs/postgres.log 2>&1 || true
          docker logs mock-newrelic > logs/mockbackend.log 2>&1 || true
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-windows
          path: docker/logs/
      
      - name: Clean up
        if: always()
        run: docker compose down -v
